import type { Metadata } from "next";
import "./globals.css";
import  josefinSans  from "@/app/fonts/font";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Assignment-seven",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefinSans.className} antialiased w-screen bg-white overflow-x-hidden text-black`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
